### ISSUE TITLE
Prod build to another directory

### ISSUE THREAD

**Issue by pitpit** [creads/cakepan#14]
When I want to build file for prod environment to another folder, I need to use `--prod --mode=prod`; which is not the best.

I think we should have new parameter `compile` to control minification of files and replace folllowing test in gulpfile.js :

    .pipe(gulpif(argv.prod !== undefined,  uglify()))

And also replace

    .pipe(gulpif(argv.prod !== undefined, rename({
      suffix: (config.version !== null) ? '-' + config.version : ''
    })))

by a simple test on `config.version` (do not concat version to file if config.version is null)

Then we can deprecate  `--prod` and only use `--mode=prod` param switcher

**Comment by samouss** [comment]
I'm okay to replace --prod to --mode=prod.

But for the "compile" parameter we don't need to add another parameters, because if we want build for prod, we must want to minified code don't you ?

**Comment by pitpit** [comment]
Do you suggest to have an internal  `prod` parameter instead of `compile` parameter that we use in prod mode env ?

ie in `prod.config.json` : 

```json
{
  "prod": true,
  "build": "../web/"
}
```

**Comment by pitpit** [comment]
{
  "version": "0.0.0",
  "prod": true,
  "build": "../web/"
}
