### ISSUE TITLE
Handle environment related configurations

### ISSUE THREAD

**Issue by pitpit** [creads/cakepan#7]
Problem : to make "--proxy" mode work with Silex or Wordpress, we must alter `build_dir` config, so it won't work anymore in "default" mode (without --proxy params)

Instead of hard-coding --prod and --proxy mode mechanism, we shoud be able to setup config related to declared environment

`gulp start --env=default` (initial setup)
`gulp start --env=proxy` (to work on top of a backend)
`gulp start --env=prod` (compile for prodduction)

**Comment by samouss** [comment]
I don't think this is the best solution, because if we want build in mode proxy with option prod ? This can't be works.
We should keep "--option" mechanism but load config file according to default (wihtout option) or proxy (with --proxy) ?
